# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "18"
  commands:
    # "docs-website/" directory was created using the command to create the site:
    # npx create-docusaurus@latest docs classic
    #
    # Install Docusaurus dependencies
    - cd docs-website/ && npm install
    # Build the site
    - cd docs-website/ && npm run build --dev
    # Copy generated files into Read the Docs directory
    - mkdir --parents _readthedocs/html/
    - cp --recursive docs-website/build/* _readthedocs/html/